site_name: Orange Cloudavenue opensource documentation

theme:
  name: material
  palette:
    - scheme: orangeCorp
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - header.autohide
    - navigation.instant
  icon:
    repo: fontawesome/brands/github-alt
  favicon: images/favicon.png
  logo: https://boosted.orange.com/docs/5.3/assets/brand/orange-logo.svg
  font: false


extra_css:
  - stylesheets/orange.css

plugins:
  - search
  - multirepo:
      cleanup: false

nav:
  - Overview: "index.md"
  - Terraform:
    - SuperSchema: '!import https://github.com/orange-cloudavenue/terraform-plugin-framework-superschema?branch=main'
    - PlanModifiers: '!import https://github.com/orange-cloudavenue/terraform-plugin-framework-planmodifiers?branch=main'
    - Validators: '!import https://github.com/orange-cloudavenue/terraform-plugin-framework-validators?branch=main'
  - ⇗ Github: "https://github.com/orange-cloudavenue"

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/orange-cloudavenue
  
copyright: Copyright &copy; 2022 - 2025 Orange Business