site_name: Orange Cloudavenue opensource documentation

theme:
  name: material
  palette:
    - scheme: orangeCorp
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - header.autohide
    - navigation.instant
  icon:
    repo: fontawesome/brands/github-alt
  favicon: https://opensource.orange.com/wp-content/themes/boosted/favicon.ico
  logo: https://boosted.orange.com/docs/5.3/assets/brand/orange-logo.svg
  font: false


extra_css:
  - stylesheets/orange.css

plugins:
  - search

nav:
  - Overview: "index.md"
  - Projects: "projects.md"
  - ⇗ Github: "https://github.com/orange-cloudavenue"

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/orange-cloudavenue
  
copyright: Copyright &copy; Orange 2025